### PR TITLE
Create 6e6a20e9fd6331ad1de5c01c6edbb453190daa47346ab885238186075465727269626C652043616B65205061727479.yaml

### PR DESCRIPTION
**Pull request by Terrible-Cake-Party**
Terrible Cake Party
TCP

### CODE REVIEW

**Comment by 0xj4m35** [comment]
@Terrible-Cake-Party your file name is in correct. It has to be policyId + tokenName

**Comment by Terrible-Cake-Party** [comment]
> @Terrible-Cake-Party your file name is in correct. It has to be policyId + tokenName

Fixed and updated. Thanks.

**Review by 0xj4m35 — DISMISSED** [review]

**Comment by 0xj4m35** [comment]
hey @Terrible-Cake-Party , your tokenName is `544350`

**Comment by 0xj4m35** [comment]
so the file name has to be `6e6a20e9fd6331ad1de5c01c6edbb453190daa47346ab88523818607544350`

**Review by 0xj4m35 — APPROVED** [review]

**Comment by Terrible-Cake-Party** [comment]
> so the file name has to be `6e6a20e9fd6331ad1de5c01c6edbb453190daa47346ab88523818607544350`

Oh, sorry, i got the 'ticker' and the "name" mixed up. i see what youre saying. thanks for your help.

**Pull request merged**
